#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""從私有的參考文獻母本生成 `docs/REFERENCES.md`（公開版）。

為什麼是生成而不是手寫
----------------------
參考文獻只有一份母本（作者私有 vault 內的 `references.md`）。公開版是它的下游快照：
刪掉只給自己看的區塊、把落地欄的私有路徑映射到本 repo 的對應位置、把驗證狀態改成
對讀者有意義的三態。手抄兩份一定會分岔，分岔的那一份遲早會把私有路徑帶出去。

所以：**公開版不手改**。`bin/gate.sh` 會用 `--check` 驗它。

兩種 --check
------------
- `--check --source <母本>`（本機／gate --full）：重新生成一次，與 `docs/REFERENCES.md`
  逐 byte 比對。生成日期沿用現有檔頭的日期，所以「今天沒改東西」不會因為換日而變紅。
- `--check`（CI／gate --public，拿不到母本）：只驗公開檔本身——生成標頭在第一行、
  沒有 private-only 標記、assert_absent 全過。

規則表在私有側
--------------
把母本改寫成公開版的那張規則表（每條 pattern 都是母本的原文）**不在這個 repo 裡**，
它跟母本一起放在私有側。理由見「步驟 4」段的註解。所以：

- 生成／`--check --source`：必須另外給 `--rules <私有規則檔>`。
- `--check`（無 `--source`，CI 用）：不需要母本，也不需要規則檔。

用法
----
    tools/build_references.py --source <私有 references.md> --rules <私有規則檔> \
        --out docs/REFERENCES.md
    tools/build_references.py --source <私有 references.md> --rules <私有規則檔> --check
    tools/build_references.py --check

exit code：0 乾淨；2 有發現；3 設定錯誤。
"""

from __future__ import annotations

import argparse
import datetime as _dt
import importlib.util
import re
import sys
from pathlib import Path

EXIT_OK = 0
EXIT_FINDINGS = 2
EXIT_CONFIG = 3

DEFAULT_OUT = Path("docs/REFERENCES.md")
HEADER_RE = re.compile(
    r"^<!-- generated by tools/build_references\.py on (\d{4}-\d{2}-\d{2}); do not edit -->$"
)
HEADER_FMT = "<!-- generated by tools/build_references.py on {date}; do not edit -->"

# 公開版不得出現的東西。`/[U]sers/` 這種寫法是故意的：字面上不出現 `/Users/`，
# 否則這支工具自己就會被 publish_check 的 L3 絕對路徑檢查抓到。
ASSERT_ABSENT = [
    ("上游原文目錄", r"02-raw/mattpocock[-]skills"),
    ("私有 review 頁", r"review-"),
    ("私有 project 卡", r"proj-"),
    ("私有 worklog", r"worklog-"),
    # 憑證清冊那一頁的**檔名**本身就是指路型洩漏，所以這裡連要擋的字面值都不寫：
    # 改成擋「任何指向 `06-reference/` 底下某一頁的引用」，`template/` 的骨架目錄除外。
    # 那一頁的頁名另外收在禁用識別字清單（L2）裡，由 HMAC 比對，不可還原。
    ("私有快查表頁", r"(?<!template/)06-reference/[a-z0-9]"),
    # `template/01-profile/` 是本 repo 真的有的骨架目錄；要擋的是指向作者私有 profile 頁的引用。
    ("私有 profile 頁", r"(?<!template/)01-profile/"),
    ("commit hash 字樣", r"(?i)commit\s+`?[0-9a-f]{7,40}\b"),
    ("裸露的 commit hash", r"`[0-9a-f]{7,40}`"),
    ("本機絕對路徑", r"/[U]sers/"),
    ("本機絕對路徑", r"/h[o]me/[a-z]"),
    ("private-only 標記", r"private-only"),
]

# 「落地位置」欄出現這些字樣時，那一段不算本 repo 內的落地實作。
NO_IMPL_PHRASES = (
    "（未公開）",
    "未隨本 repo 散布",
)

# 少數幾條的落地欄雖然指到本 repo 的檔案，講的卻是「我們刻意沒照做」。
# 這種不能標成「有落地實作」，否則圖例會說謊。
FORCE_REFERENCE_ONLY = ("Pragmatic Programmer", "course-video-manager")

IMPL_LABEL = "**本 repo 內有落地實作**"
REF_LABEL = "**僅引用**"


class BuildError(Exception):
    """母本與規則對不上——不是「掃到機敏資料」，是「這支工具該被更新了」。"""


# ---------------------------------------------------------------------------
# 規則引擎：每條規則都要說出自己命中幾次
# ---------------------------------------------------------------------------

class Rule:
    def __init__(self, name: str, pattern: str, replace: str, expect: int, flags=0):
        self.name = name
        self.pattern = pattern
        self.replace = replace
        self.expect = expect
        self.regex = re.compile(pattern, flags)

    def apply(self, text: str) -> str:
        result, count = self.regex.subn(self.replace, text)
        if count != self.expect:
            raise BuildError(
                f"規則「{self.name}」命中 {count} 次，expect {self.expect} 次。"
                "母本改過了；先看清楚改了什麼，再更新這支工具的規則，不要調 expect 了事。"
            )
        return result


def apply_rules(text: str, rules) -> str:
    for rule in rules:
        text = rule.apply(text)
    return text


# ---------------------------------------------------------------------------
# 步驟 1–3：結構手術
# ---------------------------------------------------------------------------

def drop_frontmatter(text: str) -> str:
    """公開版第一行必須是生成標頭，所以 YAML frontmatter 留著也不會被當 frontmatter
    解析。圖例改寫成正文的一節（見 LEGEND）。"""
    match = re.match(r"\A---\n.*?\n---\n", text, re.DOTALL)
    if not match:
        raise BuildError("母本開頭找不到 YAML frontmatter")
    return text[match.end():]


def strip_private_blocks(text: str, expect: int = 3) -> str:
    """刪掉成對的 private-only 區塊。

    開頭標記用 `(?<!\x60)` 排除「被反引號包起來、只是在講這個標記」的情形——母本的導讀段、
    §C managed block 那列、以及版本差異節都會提到標記本身。少了這個 lookbehind，
    第一個匹配會從導讀段一路吃到 §A 的第六列，而且**不會報錯**。
    """
    pattern = re.compile(r"(?<!`)<!-- private-only -->.*?<!-- /private-only -->", re.DOTALL)
    result, count = pattern.subn("", text)
    if count != expect:
        raise BuildError(f"private-only 區塊有 {count} 個，expect {expect} 個")
    # 整列都是 private-only 的情形會留下一行空白列，順手收掉。
    result = re.sub(r"\n[ \t]*\n[ \t]*\n", "\n\n", result)
    return result


def drop_section(text: str, heading_prefix: str, level: str = "## ") -> str:
    """刪掉某個標題底下的整節（到下一個同級或更高級標題為止）。"""
    lines = text.split("\n")
    start = None
    for index, line in enumerate(lines):
        if line.startswith(level) and heading_prefix in line:
            start = index
            break
    if start is None:
        raise BuildError(f"找不到要刪的章節：{heading_prefix}")
    end = len(lines)
    top_level = "## "
    for index in range(start + 1, len(lines)):
        if lines[index].startswith(level) or lines[index].startswith(top_level):
            end = index
            break
    # 把該節前面那條 `---` 分隔線也一起帶走
    while start > 0 and lines[start - 1].strip() in ("", "---"):
        if lines[start - 1].strip() == "---":
            start -= 1
            break
        start -= 1
    return "\n".join(lines[:start] + lines[end:])


# ---------------------------------------------------------------------------
# 步驟 4：全域文字規則（路徑映射、標籤、散文改寫）
#
# 規則表**不在這個 repo 裡**。每條 pattern 都是母本的原文，帶著私有 vault 的頁名、
# 內部計數與個人脈絡；把表放在公開檔裡，等於把要擦掉的字串原封不動印在產生器的
# 原始碼中，而三道閘門只掃產物、不掃產生器，所以會全綠著漏出去。
#
# 因此：`--source` 生成模式必須同時給 `--rules <規則檔>`（私有側）。
# ---------------------------------------------------------------------------

SPEC_KEYS = ("verified_on", "private_block_expect", "drop_sections", "e_heading",
             "label_rewrites_expect", "e_rows_min", "text_rules")


def load_spec(path: Path) -> dict:
    """載入私有規則檔（一支只含資料的 Python 模組，須匯出 `SPEC`）。"""
    if not path.is_file():
        raise BuildError(f"找不到規則檔：{path}")
    spec = importlib.util.spec_from_file_location("references_rules", path)
    if spec is None or spec.loader is None:
        raise BuildError(f"無法載入規則檔：{path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    data = getattr(module, "SPEC", None)
    if not isinstance(data, dict):
        raise BuildError(f"規則檔沒有匯出 SPEC dict：{path}")
    missing = [key for key in SPEC_KEYS if key not in data]
    if missing:
        raise BuildError(f"規則檔的 SPEC 缺少欄位：{'、'.join(missing)}")
    return data


def build_rules(entries) -> list:
    rules = []
    for entry in entries:
        rules.append(Rule(entry["name"], entry["pattern"], entry["replace"],
                          entry["expect"], entry.get("flags", 0)))
    return rules


# ---------------------------------------------------------------------------
# 步驟 5：逐列處理表格
# ---------------------------------------------------------------------------

STATE_LABEL_RE = re.compile(r"\*\*vault 內[^*]*\*\*(（[^（）]*）)?")


def split_row(line: str):
    inner = line.strip()
    if not inner.startswith("|") or not inner.endswith("|"):
        return None
    # 跳脫過的 \| 是儲存格內容，不是欄位分隔
    return [cell.strip() for cell in re.split(r"(?<!\\)\|", inner[1:-1])]


def join_row(cells) -> str:
    return "| " + " | ".join(cells) + " |"


def is_separator(cells) -> bool:
    return all(re.fullmatch(r":?-{2,}:?", cell) for cell in cells if cell)


def landing_has_implementation(landing: str, source_cell: str = "") -> bool:
    """落地欄裡還剩下可指的檔案路徑嗎？

    「同左」是母本的省略寫法，指回同一列來源欄列出的路徑，所以要往回看那一欄，
    否則整列會被誤標成「僅引用」。
    """
    stripped = landing.strip()
    if stripped.startswith("同左"):
        stripped = stripped[2:] + " " + STATE_LABEL_RE.sub("", source_cell)
    for phrase in NO_IMPL_PHRASES:
        stripped = stripped.replace(phrase, "")
    return bool(re.search(r"`[^`]+`", stripped))


def rewrite_tables(text: str, label_expect: int, e_rows_min: int) -> str:
    """A–D：依「落地位置」欄把狀態標籤改成三態。E：拿掉「引用位置」欄。"""
    lines = text.split("\n")
    out = []
    section = None
    label_rewrites = 0
    e_rows_trimmed = 0

    for line in lines:
        heading = re.match(r"^## ([A-E])\. ", line)
        if heading:
            section = heading.group(1)
        elif line.startswith("## "):
            section = None

        cells = split_row(line)
        if cells is None or section is None:
            out.append(line)
            continue

        if section == "E":
            if len(cells) != 5:
                raise BuildError(f"§E 表格列不是 5 欄：{line[:60]}")
            del cells[2]  # 引用位置欄指向私有頁，整欄不要
            e_rows_trimmed += 1
            out.append(join_row(cells))
            continue

        if is_separator(cells):
            out.append(line)
            continue
        if len(cells) != 5:
            raise BuildError(f"§{section} 表格列不是 5 欄：{line[:60]}")

        source_cell, landing = cells[0], cells[2]
        if STATE_LABEL_RE.search(source_cell):
            if any(marker in source_cell for marker in FORCE_REFERENCE_ONLY):
                label = REF_LABEL
            else:
                label = IMPL_LABEL if landing_has_implementation(landing, source_cell) else REF_LABEL
            cells[0] = STATE_LABEL_RE.sub(label, source_cell, count=1)
            label_rewrites += 1
        out.append(join_row(cells))

    if label_rewrites != label_expect:
        raise BuildError(f"狀態標籤改寫了 {label_rewrites} 列，expect {label_expect} 列")
    if e_rows_trimmed < e_rows_min:
        raise BuildError(f"§E 只處理了 {e_rows_trimmed} 列，看起來表格結構變了")
    return "\n".join(out)


# ---------------------------------------------------------------------------
# 步驟 6：§E 改頭換面
# ---------------------------------------------------------------------------

E_NEW_HEADING = "## E. 延伸閱讀（本 repo 未落地）"
E_NEW_INTRO = """這一節列出「記憶庫再往前推會撞到的既有學問」——需求工程、artifact-centric 流程、
排程、溯源、評測。**本 repo 內沒有任何一條的落地實作**，列在這裡只有一個用途：省下你重新找路的時間。
每條只給題名、URL 與一句該文獻本身的中性摘要；狀態欄只有兩種——「轉述」表示只讀過摘要或轉述，
「已上網核對」表示該日親自抓過原頁。想深讀的，從 PROV-O 與 Process Mining Manifesto 兩條開始。"""


def rebuild_e_section(text: str, e_heading: str) -> str:
    lines = text.split("\n")
    try:
        start = lines.index(e_heading)
    except ValueError as exc:
        raise BuildError("找不到 §E 標題") from exc
    end = None
    for index in range(start + 1, len(lines)):
        if lines[index].startswith("### E1."):
            end = index
            break
    if end is None:
        raise BuildError("找不到 §E 的第一個子節 E1")
    new = [E_NEW_HEADING, "", E_NEW_INTRO, ""]
    return "\n".join(lines[:start] + new + lines[end:])


def normalise_e_status(text: str, verified_on: str) -> str:
    """§E 的狀態欄只留「轉述」與「已上網核對（日期）」。"""
    lines = text.split("\n")
    out = []
    in_e = False
    for line in lines:
        if line.startswith("## "):
            in_e = line.startswith(E_NEW_HEADING)
        cells = split_row(line)
        if in_e and cells is not None and len(cells) == 4 and not is_separator(cells):
            status = cells[3]
            if status not in ("狀態",):
                if "已上網核對" in status:
                    cells[3] = f"**已上網核對（{verified_on}）**"
                else:
                    cells[3] = "轉述"
            out.append(join_row(cells))
        else:
            out.append(line)
    return "\n".join(out)


# ---------------------------------------------------------------------------
# 組裝
# ---------------------------------------------------------------------------

LEGEND = """## 驗證圖例

來源欄末尾的粗體標籤只有三種：

- **本 repo 內有落地實作** — 這條來源借來的做法，在本 repo 內有對應的檔案可以讀、可以跑；
  對應位置就寫在同一列的「落地位置」欄。
- **僅引用** — 本 repo 只有摘要或連結，沒有對應實作；原始判斷留在作者的私有記憶庫，未公開。
- **已上網核對（YYYY-MM-DD）** — 該日親自抓取原頁，核對題名、授權與版本。星數、版本號這類會變的欄位
  只是當日快照，以原頁為準；標「待核對」的就是還沒查到，不補造。

沒有 URL 的地方就是找不到。「刻意不採用什麼」欄跟「借了什麼概念」欄一樣重要——
這頁一半的價值在於記下哪些東西看起來該裝、但本 vault 決定不裝，以及為什麼。
"""


def build(source_text: str, date: str, spec: dict) -> str:
    text = drop_frontmatter(source_text)
    text = strip_private_blocks(text, spec["private_block_expect"])

    # 只對作者自己有意義（或直接指向私有頁）的章節，整節刪；哪幾節由規則檔決定
    for heading_prefix, level in spec["drop_sections"]:
        text = drop_section(text, heading_prefix, level=level)

    text = rebuild_e_section(text, spec["e_heading"])
    text = apply_rules(text, build_rules(spec["text_rules"]))
    text = rewrite_tables(text, spec["label_rewrites_expect"], spec["e_rows_min"])
    text = normalise_e_status(text, spec["verified_on"])

    # 標題後面插入圖例節
    title = "# References — 方法論與工具的外部來源"
    if title not in text:
        raise BuildError("找不到主標題")
    lines = text.split("\n")
    anchor = lines.index("## 怎麼讀這頁")
    lines = lines[:anchor] + LEGEND.split("\n") + [""] + lines[anchor:]
    text = "\n".join(lines)

    body = HEADER_FMT.format(date=date) + "\n\n" + text.lstrip("\n")
    body = re.sub(r"\n{3,}", "\n\n", body)
    if not body.endswith("\n"):
        body += "\n"
    return body


# ---------------------------------------------------------------------------
# 檢查
# ---------------------------------------------------------------------------

def check_public_file(text: str, label: str) -> list:
    findings = []
    lines = text.split("\n")
    if not lines or not HEADER_RE.match(lines[0]):
        findings.append(f"ERROR {label}:1 第一行不是生成標頭"
                        "（`<!-- generated by tools/build_references.py on YYYY-MM-DD; do not edit -->`）")
    for name, pattern in ASSERT_ABSENT:
        regex = re.compile(pattern)
        for line_no, line in enumerate(lines, 1):
            if regex.search(line):
                findings.append(f"ERROR {label}:{line_no} assert_absent 命中：{name}")
                break
    return findings


def header_date(text: str) -> str | None:
    first = text.split("\n", 1)[0]
    match = HEADER_RE.match(first)
    return match.group(1) if match else None


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        prog="build_references.py",
        description="從私有母本生成公開版 docs/REFERENCES.md（公開版不手改）。",
    )
    parser.add_argument("--source", help="私有參考文獻母本（references.md）")
    parser.add_argument("--rules", help="私有規則檔（匯出 SPEC 的 Python 模組）；"
                                        "只要給了 --source 就必須給")
    parser.add_argument("--out", default=str(DEFAULT_OUT),
                        help=f"輸出路徑（預設 {DEFAULT_OUT}）")
    parser.add_argument("--check", action="store_true",
                        help="不寫檔；有 --source 就重生成比對，沒有就只驗公開檔本身")
    parser.add_argument("--date", help="生成日期（預設今天；--check 會沿用現有檔頭的日期）")
    args = parser.parse_args(argv)

    out_path = Path(args.out)

    if args.check:
        if not out_path.is_file():
            print(f"ERROR 找不到 {out_path}", file=sys.stderr)
            return EXIT_FINDINGS
        current = out_path.read_text(encoding="utf-8")
        findings = check_public_file(current, out_path.as_posix())
        if args.source:
            source_path = Path(args.source)
            if not source_path.is_file():
                print(f"ERROR 找不到母本：{source_path}", file=sys.stderr)
                return EXIT_CONFIG
            if not args.rules:
                print("ERROR --source 必須搭配 --rules（規則表在私有側，不在本 repo）",
                      file=sys.stderr)
                return EXIT_CONFIG
            date = args.date or header_date(current) or _dt.date.today().isoformat()
            try:
                spec = load_spec(Path(args.rules))
                rebuilt = build(source_path.read_text(encoding="utf-8"), date, spec)
            except BuildError as exc:
                print(f"ERROR 依母本重生成失敗：{exc}", file=sys.stderr)
                return EXIT_FINDINGS
            if rebuilt != current:
                findings.append(
                    f"ERROR {out_path.as_posix()} 與母本重生成的結果不一致"
                    "（公開版被手改了，或母本改了但沒重跑這支工具）")
        if findings:
            for line in findings:
                print(line)
            print(f"\n{len(findings)} error(s)")
            return EXIT_FINDINGS
        mode = "重生成比對" if args.source else "公開檔自檢（無母本）"
        print(f"OK 0 error(s)；{out_path.as_posix()} 通過{mode}。")
        return EXIT_OK

    if not args.source:
        print("ERROR 生成模式必須給 --source", file=sys.stderr)
        return EXIT_CONFIG
    if not args.rules:
        print("ERROR 生成模式必須給 --rules（規則表在私有側，不在本 repo）", file=sys.stderr)
        return EXIT_CONFIG
    source_path = Path(args.source)
    if not source_path.is_file():
        print(f"ERROR 找不到母本：{source_path}", file=sys.stderr)
        return EXIT_CONFIG
    date = args.date or _dt.date.today().isoformat()
    try:
        spec = load_spec(Path(args.rules))
        result = build(source_path.read_text(encoding="utf-8"), date, spec)
    except BuildError as exc:
        print(f"ERROR {exc}", file=sys.stderr)
        return EXIT_FINDINGS

    findings = check_public_file(result, out_path.as_posix())
    if findings:
        for line in findings:
            print(line)
        print(f"\n{len(findings)} error(s)；沒有寫出任何東西。")
        return EXIT_FINDINGS

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(result, encoding="utf-8")
    print(f"OK 0 error(s)；已寫出 {out_path.as_posix()}（{len(result.splitlines())} 行）。")
    return EXIT_OK


if __name__ == "__main__":
    sys.exit(main())
